%generateIcon  Generate icon and splash screen for MATLAB Arcade.
%   Creates:
%       packaging/icon.png    — 256x256 app icon (neon "A" on dark background)
%       packaging/splash.png  — 640x480 splash screen ("MATLAB ARCADE" title)
%
%   The .png icon works directly with compiler.build.standaloneApplication.
%   For a .ico file (Windows shortcut icon), convert icon.png using:
%       - Online: https://convertio.co/png-ico/ or https://icoconvert.com/
%       - ImageMagick: magick convert icon.png -define icon:auto-resize icon.ico
%       - MATLAB File Exchange: "png2ico" or "img2ico"
%
%   Usage:
%       cd packaging
%       generateIcon
%
%   See also buildExecutable

scriptDir = fileparts(mfilename("fullpath"));

%% Color palette (matching Arcade.m neon theme)
bgColor = [0.015, 0.015, 0.03];
neonCyan = [0, 0.92, 1];
glowCyan = [0, 0.45, 0.55];

%% ===== ICON (256x256) =====
fprintf("Generating icon.png (256x256)...\n");

fig = figure("Visible", "off", ...
    "Color", bgColor, ...
    "Units", "pixels", ...
    "Position", [100, 100, 256, 256], ...
    "MenuBar", "none", ...
    "ToolBar", "none");

ax = axes(fig, ...
    "Units", "normalized", ...
    "Position", [0, 0, 1, 1], ...
    "Color", bgColor, ...
    "XColor", "none", ...
    "YColor", "none", ...
    "XLim", [0, 1], ...
    "YLim", [0, 1]);
hold(ax, "on");

% Draw the Asteroids ship wireframe (triangle/arrow) as the icon
% Ship vertices — a forward-pointing arrow/chevron
shipX = [0.50, 0.22, 0.38, 0.50, 0.62, 0.78, 0.50];
shipY = [0.85, 0.18, 0.32, 0.25, 0.32, 0.18, 0.85];

% Outer glow (thick, dim)
plot(ax, shipX, shipY, "-", ...
    "Color", [glowCyan, 0.35], ...
    "LineWidth", 10);

% Mid glow
plot(ax, shipX, shipY, "-", ...
    "Color", [glowCyan, 0.6], ...
    "LineWidth", 5);

% Core line (bright neon)
plot(ax, shipX, shipY, "-", ...
    "Color", neonCyan, ...
    "LineWidth", 2.5);

hold(ax, "off");

iconPath = fullfile(scriptDir, "icon.png");
exportgraphics(fig, iconPath, "Resolution", 256);
close(fig);
fprintf("  Saved: %s\n\n", iconPath);

%% ===== SPLASH SCREEN (640x480) =====
fprintf("Generating splash.png (640x480)...\n");

fig = figure("Visible", "off", ...
    "Color", bgColor, ...
    "Units", "pixels", ...
    "Position", [100, 100, 640, 480], ...
    "MenuBar", "none", ...
    "ToolBar", "none");

ax = axes(fig, ...
    "Units", "normalized", ...
    "Position", [0, 0, 1, 1], ...
    "Color", bgColor, ...
    "XColor", "none", ...
    "YColor", "none", ...
    "XLim", [0, 640], ...
    "YLim", [0, 480]);
hold(ax, "on");

% Starfield background (scattered dim dots)
rng(42);  % reproducible
nStars = 120;
starX = rand(nStars, 1) * 640;
starY = rand(nStars, 1) * 480;
starSz = rand(nStars, 1) * 8 + 1;
starAlpha = rand(nStars, 1) * 0.5 + 0.1;
scatter(ax, starX, starY, starSz, ...
    repmat([0.6, 0.7, 0.8], nStars, 1), "filled", ...
    "MarkerFaceAlpha", mean(starAlpha));

% Decorative horizontal line
lineY = 215;
plot(ax, [80, 560], [lineY, lineY], "-", ...
    "Color", [glowCyan, 0.3], ...
    "LineWidth", 3);
plot(ax, [80, 560], [lineY, lineY], "-", ...
    "Color", neonCyan, ...
    "LineWidth", 1);

% Title glow shadow
text(ax, 320, 310, "M A T L A B", ...
    "FontSize", 28, ...
    "FontWeight", "bold", ...
    "Color", [glowCyan, 0.4], ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", ...
    "FontName", "Consolas");

% Title bright
text(ax, 320, 310, "M A T L A B", ...
    "FontSize", 28, ...
    "FontWeight", "bold", ...
    "Color", neonCyan, ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", ...
    "FontName", "Consolas");

% "ARCADE" large text — glow
text(ax, 320, 260, "A  R  C  A  D  E", ...
    "FontSize", 44, ...
    "FontWeight", "bold", ...
    "Color", [glowCyan, 0.3], ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", ...
    "FontName", "Consolas");

% "ARCADE" large text — bright
text(ax, 320, 260, "A  R  C  A  D  E", ...
    "FontSize", 44, ...
    "FontWeight", "bold", ...
    "Color", neonCyan, ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", ...
    "FontName", "Consolas");

% Subtitle
text(ax, 320, 170, "15 Classic & Original Games", ...
    "FontSize", 14, ...
    "Color", [0.5, 0.55, 0.6], ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", ...
    "FontName", "Consolas");

% Version / credit line
text(ax, 320, 50, "Built with MATLAB", ...
    "FontSize", 11, ...
    "Color", [0.3, 0.35, 0.4], ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", ...
    "FontName", "Consolas");

hold(ax, "off");

splashPath = fullfile(scriptDir, "splash.png");
exportgraphics(fig, splashPath, "Resolution", 150);
close(fig);
fprintf("  Saved: %s\n\n", splashPath);

fprintf("=== Icon and splash generation complete ===\n");
fprintf("\nTo convert icon.png to icon.ico for Windows:\n");
fprintf("  Option 1: https://convertio.co/png-ico/\n");
fprintf("  Option 2: magick convert icon.png -define icon:auto-resize icon.ico\n");
fprintf("  Option 3: MATLAB File Exchange 'png2ico'\n");
